from telegram import Update
from telegram.ext import Application, CommandHandler, CallbackContext
import random

TOKEN = "" #insert token

async def start(update: Update, context: CallbackContext):
    await update.message.reply_text("Hello! I'm your bot! Use /help to see commands.")

async def cheat(update: Update, context: CallbackContext):
    await update.message.reply_text("Caught ya! No cheating allowed. 🚨")

async def rickroll(update: Update, context: CallbackContext):
    await update.message.reply_text("Never gonna give you up! 🎶 https://youtu.be/dQw4w9WgXcQ")

async def mood(update: Update, context: CallbackContext):
    moods = ["You're on top of the world! 🌟", "Eh, could be worse. 😐", "It's all downhill from here... 😭", "You're feeling like dirt. 😔"]
    await update.message.reply_text(random.choice(moods))

async def flip(update: Update, context: CallbackContext):
    result = random.choice(["Heads!", "Tails!"])
    await update.message.reply_text(f"Coin flip result: {result}")

async def insult(update: Update, context: CallbackContext):
    insults = [
        "You're slower than dial-up internet. 🐌",
        "If brain cells were currency, you'd be bankrupt. 💸",
        "You're so lost, even Google Maps can't find you. 🗺️",
        "You're like a broken pencil, pointless and useless. 📝",
        "You're so ugly, when you look in the mirror, your reflection looks away. 👀",
        "Your inferiority complex is fully justified. 🤷‍♂️",
    ]
    await update.message.reply_text(random.choice(insults))

async def death(update: Update, context: CallbackContext):
    result = random.choice(["RIPPPP", "Damn. You're alive."])
    await update.message.reply_text(f"Let's see how lucky you are: {result}")
    if result == "RIPPPP":
        deaths = [
            "You died of natural causes. 💀",
            "You died of a heart attack. 💔 As in someone came up to you with a knife and attacked your heart.",
            "You died of a stroke. 💉 The person dialling 995 dropped their phone into a drain.",
            "You died of a car crash. 🚗 Should've worn that seatbelt.",
            "You died of a plane crash. 🛫 At least you went out on a high.",
            "You died in a fire. 🔥 Shouldn't have been playing with those matches.",
            "You died from a bomb. 💣 Why'd you press that big red button?",
            "You died in a tornado. ⛈️",
            "You died in a volcano eruption. 🌋",
            "You died in a nuclear explosion. 💥 Like, you were the ONLY one who died.",
            "You died in a global warming event. 🌎",
            "You died in a natural disaster. 🌩️",
            "You died of dysentery. 🦠 Shouldn't have drank from that sewer.",
        ]
        await update.message.reply_text(random.choice(deaths))
    else:
        await update.message.reply_text("I'll get you next time. 😉")
    

emoji_dict = {
        "hello": "👋",
        "goodbye": "👋",
        "thank you": "🙏",
        "want": "🙏",
        "to": "2️⃣",
        "same": "🤝",
        "now": "🕒👇",
        "this": "👇",
        "way": "🛣️",
        "np": "🙌",
        "blood": "🩸",
        "bloody": "🩸",
        "sweat": "💦",
        "omg": "😮",
        "attach": "📎",
        "here": "📍",
        "spray": "💦",
        "tear": "💧",
        "welcome": "🙌",
        "wishes": "🙏",
        "wish": "🙏",
        "sorry": "😥",
        "love": "❤️",
        "hi": "👋",
        "bye": "👋",
        "thanks": "🙏",
        "sry": "😥",
        "luv": "❤️",
        "hey": "👋",
        "see you": "👋",
        "see ya": "👋",
        "see you later": "👋",
        "see ya later": "👋",
        "see you soon": "👋",
        "see ya soon": "👋",
        "he": "👦",
        "she": "👧",
        "they": "👨‍👩‍👧‍👦",
        "them": "👨‍👩‍👧‍👦",
        "their": "👨‍👩‍👧‍👦",
        "her": "👩",
        "him": "👨",
        "themselves": "👨‍👩‍👧‍👦",
        "you": "🫵",
        "your": "🫵",
        "yours": "🫵",
        "yourself": "🫵",
        "you're": "🫵",
        "you've": "🫵",
        "you'll": "🫵",
        "you'd": "🫵",
        "you've": "🫵",
        "youre": "🫵",
        "i": "🧒",
        "me": "🧒",
        "my": "🧒",
        "mine": "🧒",
        "im": "🧒",
        "i'm": "🧒",
        "we": "👨‍👩‍👧‍👦",
        "us": "👨‍👩‍👧‍👦"
        "our": "👨‍👩‍👧‍👦",
        "i'd": "🧒",
        "i've": "🧒",
        "i'll": "🧒",

        #hand gesture
        "good": "👍",
        "like": "👍",
        "bad": "👎",
        "dislike": "👎",
        "great": "👏",
        "ok": "👌",
        "yea": "👌",
        "yeah": "👌",
        "ye": "👌",
        "okay": "👌",
        "fist bump": "👊",
        "peace": "✌️",
        "hope": "🤞",
        "awesome": "🤘",
        "praying": "🙏",
        "handshake": "🤝",
        "point up": "☝️",
        "um actually": "☝️",
        "point down": "👇",
        "go down": "👇",
        "go up": "☝️",
        "go up a bit": "☝️",
        "go down a bit": "👇",
        "go left": "👈",
        "go right": "👉",
        "point left": "👈",
        "point right": "👉",
        "go": "👉",

        #question words
        "what": "🤷‍♀️",
        "how": "🤷‍♀️",
        "why": "🤷‍♀️",
        "who": "🤷‍♀️",
        "when": "🤷‍♀️",
        "where": "🤷‍♀️",
        "which": "🤷‍♀️",
        "whom": "🤷‍♀️",
        "whomst": "🤷‍♀️",
        "whatever": "🤦‍♂️",
        "whatever you say": "🤦‍♂️",
        "selfie": "🤳",
        "dance": "💃",
        "sing": "🎤",
        "dancer": "💃",
        "kneel": "🧎‍➡️",

        #emotions
        "party": "🥳",
        "yay": "🎉",
        "hungry": "😋",
        "delicious": "😋",
        "yum": "😋",
        "drooling": "🤤",
        "yummy": "🤤",
        "smile": "😊",
        "happy": "😃",
        "yay": "😁",
        "lol": "😂",
        "laugh": "😂",
        "haha": "😂",
        "wow": "😮",
        "excited": "😄",
        "cry": "😭",
        "sad": "😢",
        "angry": "😡",
        "mad": "😠",
        "shocked": "😲",
        "surprised": "😮",
        "oh": "😲",
        "o": "😲",
        "blush": "😊",
        "cool": "😎",
        "nerd": "🤓",
        "silly": "🤪",
        "sleepy": "😴",
        "sick": "🤒",
        "vomit": "🤮",
        "dizzy": "😵",
        "skull": "💀",
        "dead": "💀",
        "poop": "💩",
        "poo": "💩",
        "crap" : "💩",
        "ded": "💀",
        "rip": "💀",
        "died": "💀",
        "die": "💀",
        "dying": "💀",
        "ghost": "👻",
        "aww": "😍",
        "kiss": "😘",
        "kissing": "😘",
        "kisses": "💋",
        "hug": "🤗",
        "cupid": "💘",
        "think": "🤔",
        "nerd": "🤓",
        "monocle": "🧐",
        "observe" : "👀",
        "see" : "👀",
        "seem": "🧐",
        "mind blown": "🤯",
        "sus": "🕴",
        "suspicious": "🕴",
        "relax": "💆",
        "massage": "💆",
        "haircut": "💇",
        "nailpolish": "💅",
        "nail polish": "💅",
        "manipedi": "💅",
        "manicure": "💅",
        "pedicure": "💅",
        "nails done": "💅",
        "gossip": "💅",
        "zesty": "💅",
        "listen": "🧏",
        "hear": "🧏",
        "damn": "🤦",
        "goddamn": "🤦",
        "smh": "🤦",
        "shut up": "🤦",
        "idk": "🤷",
        "i don't know": "🤷",
        "i dunno": "🤷",
        "i dont know": "🤷",
        "i don't care": "🤷",
        "i dont care": "🤷",
        "i don't understand": "🤷",
        "i dont understand": "🤷",
        "idc": "🤷",
        "dont": "🙅‍♀️",
        "don't": "🙅‍♀️",
        "do not": "🙅‍♀️",
        "shaking my head": "🤦",
        "bored": "😒",
        "boring": "😒",
        "boredom": "😒",
        "confused": "😕",
        "tired": "😴",
        "sleepy": "😴",
        "sleep": "😴",
        "asleep": "😴",
        "work": "💼",
        "study": "📚",
        "homework": "📚",
        "home" : "🏠",
        "min": "🕒",
        "sec": "🕒",
        "minute": "🕒",
        "second": "🕒",
        "mins": "🕒",
        "secs": "🕒",
        "baby": "👶",
        "couple": "👫",
        "big": "🐘",
        "small": "🐜",
        "hot": "🥵",
        "cold": "🥶",
        "warm": "🥵",
        "cool": "🥶",
        "freezing": "🥶",
        "hotter": "🥵",
        "colder": "🥶",
        "warmer": "🥵",
        "cooler": "🥶",
        "eww": "🤮",
        "ew": "🤮",
        "yuck": "🤮",
        "shh": "🤫",
        "shhh": "🤫",
        "quiet": "🤫",
        "absent": "🫥",
        "hurt": "🤕",
        "injured": "🤕",
        "quirky": "🤪",
        "huh": "🤔",
        "wait what": "🤔",
        "grr": "😡",
        "grrr": "😡",
        "achoo": "🤧",
        "ouch": "🤕",
        "ow": "🤕",
        "oh dear": "😰",
        "mwahaha": "😈",
        "rich": "🤑",
        "greed": "🤑",
        "greedy": "🤑",
        "liar": "🤥",
        "lie": "🤥",
        "lies": "🤥",
        "cute": "🥹",
        "cutey": "🥹",
        "cuteee": "🥹",
        "cutee": "🥹",
        "cutie": "🥹",
        "adorable": "🥰",
        "angel": "👼",
        "angelic": "👼",
        "huh": "🤔",
        "hmm": "🤔",
        "swear": "😡",
        "oops": "🫢",


        #people
        "family": "👨‍👩‍👧‍👦",
        "twins": "🧑‍🤝‍🧑",
        "parents": "👨‍👩‍👧",
        "siblings": "👩‍👩‍👦",
        "mother": "👩‍👦",
        "father": "👨‍👦",
        "grandparents": "👵👴",
        "grandmother": "👵",
        "grandfather": "👴",
        "brother": "👦",
        "sister": "👧",
        "grandma": "👵",
        "grandpa": "👴",
        "uncle": "👴",
        "aunt": "👵",
        "mom": "👩‍👦",
        "dad": "👨‍👦",
        "mum": "👩‍👦",
        "daddy": "👨‍👦",
        "mummy": "👩‍👦",
        "mommy": "👩‍👦",
        "ma": "👨‍👦",
        "pa": "👨‍👦",
        "da": "👨‍👦",
        "blond": "👱",
        "curly hair": "🧑‍🦱",
        "red hair": "🧑‍🦰",
        "bald": "🧑‍🦲",
        "white hair": "🧑‍🦳",
        "zombie": "🧟",
        "vampire": "🧛",
        "genie": "🧞",
        "mermaid": "🧜",
        "elf": "🧝",
        "alien": "👽",
        "ogre": "👹",
        "devil": "😈",
        "ear": "👂",
        "eye": "👁️",
        "nose": "👃",
        "smell": "👃",
        "mouth": "👄",
        "tongue": "👅",
        "lip": "👄",
        "teeth": "🦷",
        "taste": "👅",
        "brain": "🧠",
        "mind": "🧠",
        "hand": "🖐️",
        "hi five": "🖐️",
        "foot": "🦶",
        "leg": "🦵",
        "kick": "🦵",
        "robot arm": "🦾",
        "robot leg": "🦿",
        "robot": "🤖",
        "clown": "🤡",
        "wizard": "🧙",
        "ninja": "🥷",
        "superhero": "🦸",
        "supervillain": "🦹",
        "crown": "👑",
        "top hat": "🎩",
        "scarf": "🧣",
        "glasses": "👓",
        "sunglasses": "🕶️",
        "mask": "😷",

        #symbols
        "up": "⬆️",
        "down": "⬇️",
        "left": "⬅️",
        "right": "➡️",
        "north": "⬆️",
        "south": "⬇️",
        "west": "⬅️",
        "east": "➡️",
        "double up": "⏫",
        "double down": "⏬",
        "back": "🔙",
        "end": "🔚",
        "on": "🔛",
        "soon": "🔜",
        "top": "🔝",
        "plus": "➕",
        "and": "➕",
        "add": "➕",
        "minus": "➖",
        "multiply": "✖️",
        "divide": "➗",
        "equals": "🟰",
        "infinity": "♾️",
        "forever": "♾️",
        "cross": "✝️",
        "star of david": "✡️",
        "om": "🕉️",
        "yin yang": "☯️",
        "wheel of dharma": "☸️",
        "peace": "☮️",
        "menorah": "🕎",
        "islam": "☪️",
        "aries": "♈",
        "taurus": "♉",
        "gemini": "♊",
        "cancer": "♋",
        "leo": "♌",
        "virgo": "♍",
        "libra": "♎",
        "scorpio": "♏",
        "sagittarius": "♐",
        "capricorn": "♑",
        "aquarius": "♒",
        "pisces": "♓",
        "danger": "⚠️",
        "warning": "⚠️",
        "warn": "⚠️",
        "prohibited": "🚫",
        "no entry": "⛔",
        "stop": "🛑",
        "check": "✔️",
        "cross": "❌",
        "wrong": "❌",
        "x": "❌",
        "no": "❌",
        "checkmark": "✅",
        "yes": "✅",
        "tick": "✅",
        "correct": "✅",
        "can": "✅",
        "zero": "0️⃣",
        "one": "1️⃣",
        "two": "2️⃣",
        "three": "3️⃣",
        "four": "4️⃣",
        "five": "5️⃣",
        "six": "6️⃣",
        "seven": "7️⃣",
        "eight": "8️⃣",
        "nine": "9️⃣",
        "ten": "🔟",
        "10" : "🔟",
        "0": "0️⃣",
        "1" : "1️⃣",
        "2" : "2️⃣",
        "3" : "3️⃣",
        "4" : "4️⃣",
        "5" : "5️⃣",
        "6" : "6️⃣",
        "7" : "7️⃣",
        "8" : "8️⃣",
        "9" : "9️⃣",
        "turn": "🔄",
        "repeat": "🔁",
        "loop": "🔁",
        "reverse": "🔃",
        "shuffle": "🔀",
        "spin": "🔄",
        "random": "🎲",
        "copyright": "©️",
        "registered": "®️",
        "trade": "™️",
        "paragraph": "¶",
        "section": "§",
        "recycle": "♻️",
        "biohazard": "☣️",
        "radioactive": "☢️",
        "perfect": "💯",
        "new": "🆕",
        "free": "🆓",
        "internet": "🌐",
        "wifi": "🌐",
        "pause": "⏸️",
        "start": "▶️",
        "!": "❗",
        "!!": "‼️",
        "?": "❓",
        "question": "❓",
        "!?": "⁉️",
        "interrobang": "⁉️",
        "hash": "#️⃣",
        "#": "#️⃣",
        "number": "🔢",
        "hashtag": "#️⃣",
        "*": "*️⃣",
        "heartbroken": "💔",
        "next": "⏭️",
        "previous": "⏮️",
        "fast forward": "⏩",
        "rewind": "⏪",
        "red": "🟥",
        "orange": "🟧",
        "yellow": "🟨",
        "green": "🟩",
        "blue": "🟦",
        "purple": "🟪",
        "brown": "🟫",
        "black": "⬛",
        "white": "⬜",
        "gray": "🩶",  # This one looks a little grayish
        "pink": "🩷",
        "beige": "🟫",  # (this is more brown but can pass for beige!)
        "gold": "🥇",    # It’s not as shiny as gold, but we can work with it!
        "silver": "🥈",  # Silver coin emoji!
        "turquoise": "🟩",  # Close enough to turquoise, right?
        "indigo": "🟦",


        #jobs
        "doctor": "🧑‍⚕️",
        "nurse": "👩‍⚕️",
        "teacher": "🧑‍🏫",
        "scientist": "🧑‍🔬",
        "engineer": "🧑‍💻",
        "artist": "🧑‍🎨",
        "musician": "🧑‍🎤",
        "chef": "👨‍🍳",
        "pilot": "👨‍✈️",
        "astronaut": "🧑‍🚀",
        "police officer": "👮",
        "firefighter": "👨‍🚒",
        "judge": "🧑‍⚖️",
        "farmer": "👩‍🌾",
        "construction worker": "👷",
        "detective": "🕵️",
        "soldier": "🪖",
        "lawyer": "👨‍⚖️",
        "law" : "👨‍⚖️",
        "justice" : "👨‍⚖️",
        "fair" : "👨‍⚖️",

        #food
        "slice of pizza": "🍕",
        "slice": "🍕",
        "fortune cookie": "🥠",
        "mooncake": "🥮",
        "pizza": "🍕",
        "hamburger": "🍔",
        "hotdog": "🌭",
        "sandwich": "🥪",
        "taco": "🌮",
        "burrito": "🌯",
        "salad": "🥗",
        "soup": "🍲",
        "stew": "🍲",
        "curry": "🍛",
        "broth": "🍲",
        "bowl": "🥣",
        "cookie": "🍪",
        "chocolate": "🍫",
        "ice cream": "🍦",
        "candy": "🍬",
        "popcorn": "🍿",
        "popsicle": "🍧",
        "soda": "🥤",
        "beer": "🍺",
        "snowcone": "🍧",
        "sundae": "🍨",
        "milkshake": "🥛",
        "smoothie": "🥤",
        "milk": "🥛",
        "juice": "🧃",
        "wine": "🍷",
        "cheers": "🍻",
        "champagne": "🍾",
        "congrats": "🍾",
        "tropical drink": "🍹",
        "beverage": "🍹",
        "drink": "🍹",
        "cup of tea": "🍵",
        "tea cup": "🍵",
        "tea": "🍵",
        "coffee": "☕",
        "mug": "🍵",
        "cup": "🍵",
        "spill": "🫗",
        "pour": "🫗",
        "spilled": "🫗",
        "spilt": "🫗",
        "whiskey": "🥃",
        "bourbon": "🥃",
        "cutlery": "🍴",
        "fork": "🍴",
        "knife": "🔪",
        "spoon": "🥄",
        "salt": "🧂",
        "pepper": "🧂",
        "spice": "🌶️",
        "plate": "🍽️",
        "takeout": "🥡",
        "takeaway": "🥡",
        "chopsticks": "🍽️",
        "ice": "🧊",
        "chill": "🧊",
        "icy": "🧊",
        "honey": "🍯",
        "peanut": "🥜",
        "hazelnut": "🌰",
        "nutella": "🌰",
        "cheese": "🧀",
        "egg": "🥚",
        "omelette": "🍳",
        "naan": "🫓",
        "pita": "🫓",
        "bread": "🍞",
        "baguette": "🥖",
        "croissant": "🥐",
        "pretzel": "🥨",
        "bagel": "🥯",
        "bone": "🦴",
        "frying pan": "🍳",
        "pan": "🥘",
        "pot": "🍲",
        "potato": "🥔",
        "carrot": "🥕",
        "onion": "🧅",
        "garlic": "🧄",
        "ginger": "🫚",
        "lemon": "🍋",
        "tomato": "🍅",
        "cucumber": "🥒",
        "sweet potato": "🍠",
        "peach": "🍑",
        "pear": "🍐",
        "apple": "🍎",
        "banana": "🍌",
        "pineapple": "🍍",
        "watermelon": "🍉",
        "grapes": "🍇",
        "strawberry": "🍓",
        "blueberry": "🫐",
        "raspberry": "🍒",
        "blackberry": "🫐",
        "kiwi": "🥝",    
        "mango": "🥭",    
        "papaya": "🥭",  
        "corn": "🌽",
        "maize": "🌽",
        "pea pod": "🫛",
        "pea": "🫛",
        "bean": "🫘",
        "chickpea": "🫘",
        "peapod": "🫛",
        "pod": "🫛",
        "broccoli": "🥦",
        "cabbage": "🥬",
        "cauliflower": "🥬",
        "pickle": "🥒",
        "capsicum": "🫑",
        "flapjack": "🥞",
        "flap": "🥞",
        "pancake": "🥞",
        "waffle": "🧇",
        "cheeseburger": "🍔",
        "bacon": "🥓",
        "ham": "🍖",
        "burger": "🍔",
        "melt": "🥵",
        "hot": "🥵",
        "lollipop": "🍭",
        "candy cane": "🍭",
        "pie": "🥧",
        "cream": "🍦",
        "boba": "🧋",
        "jar": "🫙",
        "jug": "🍶",
        "pudding": "🍮",
        "jelly": "🍮",
        "doughnut": "🍩",
        "donut": "🍩",
        "nut": "🥜",
        "winnie the pooh": "🐻",
        "pooh": "🐻",
        "sushi": "🍣",
        "ramen": "🍜",
        "udon": "🍜",
        "onigiri": "🍙",
        "tempura": "🍤",
        "sashimi": "🍣",
        "gyoza": "🥟",
        "dumpling": "🥟",
        "fried rice": "🍚",
        "curry rice": "🍛",
        "rice": "🍚",
        "tamale": "🫔",
        "bento": "🍱",
        "clam chowder": "🦪",
        "clam": "🦪",
        "pearl": "🦪",
        "shellfish": "🦪",
        "oyster": "🦪",
        "abalone": "🦪",
        "mollusc": "🦪",
        "mussel": "🦪",
        "skewer": "🍡",
        "kebab": "🍢",
        "birthday cake": "🎂",
        "bday cake": "🎂",
        "cupcake": "🧁",
        "cake": "🍰",
        "lime": "🍋‍🟩",
        "melon": "🍉",
        "honeydew": "🍈",
        "coconut": "🥥",
        "avocado": "🥑",
        "brinjal": "🍆",
        "eggplant": "🍆",
        "spicy": "🌶️",
        "oily": "🧈",
        "bitter": "🍵",
        "fatty": "🧈",
        "buttery": "🧈",
        "steak": "🥩",
        "steakhouse": "🥩",
        "meat": "🥩",
        "drumstick": "🍗",
        "beef": "🥩",
        "pork": "🍖",
        "dry": "🦴",
        "raw": "🦴",
        "truffle": "🧆",
        "wrap": "🌯",
        "meal": "🍽",
        "lunch": "🥪",
        "dinner": "🥘",
        "breakfast": "🍳",
        "snack": "🍟",
        "food": "🍔",
        "eat": "🍽",
        "pasta": "🍝",
        "spaghetti": "🍝",
        "linguine": "🍝",
        "fettucine": "🍝",
        "alfredo": "🍝",
        "chili pepper": "🌶️",
        "chili": "🌶️",
        "baby formula": "🍼",
        "formula": "🍼",
        "soda pop": "🍹",
        "cocktail": "🍸",
        "knot": "🧣",
        "cheddar": "🧀",
        "parmesan": "🧀",
        "mozzarella": "🧀",
        "ricotta": "🧀",
        "roti": "🫓",
        "rotisserie": "🍗",
        "noodles": "🍜",
        "noodle": "🍜",
        "teapot": "🫖",
        "dish": "🍽",
        "dishes": "🍽",

        #activities
        "talk": "💬",
        "speak": "🗣",
        "relationship": "👫",
        "stand": "🧍",
        "walk": "🚶‍♀️‍➡️",
        "play": "🎮",
        "game": "🎮",
        "sport": "⚽️",
        "football": "⚽️",
        "basketball": "🏀",
        "volleyball": "🏐",
        "swim": "🏊‍♂️",
        "swimming": "🏊‍♂️",
        "surf": "🏄‍♂️",
        "parachute": "🪂",
        "ski": "⛷️",
        "snowboard": "🏂",
        "weight": "🏋️‍♂️",
        "weightlift": "🏋️‍♂️",
        "yoga": "🧘‍♂️",
        "meditate": "🧘‍♂️",
        "pilates": "🧘‍♂️",
        "meditation": "🧘‍♂️",
        "mindfulness": "🧘‍♂️",
        "cartwheel": "🤸‍♀️",
        "gymnastics": "🤸‍♂️",
        "karate": "🤼‍♀️",
        "martial arts": "🤼‍♂️",
        "gym": "🏋️‍♀️",
        "gymnast": "🤸‍♀️",
        "roller skate": "🛼",
        "sled": "🛷",
        "sleigh ride": "🛷",
        "sleigh": "🛷",
        "lift": "🏋️",
        "fishing": "🎣",
        "scuba diving": "🤿",
        "snorkel": "🤿",
        "swimsuit": "🧕",
        "iceskate": "⛸️",
        "ice skate": "⛸️",
        "skate" : "⛸️",
        "hockey": "🏒",
        "golf": "⛳",
        "squash": "🏒",
        "archery": "🏹",
        "shoot": "🏹",
        "table tennis": "🎾",
        "tennis": "🎾",
        "ping pong": "🏓",
        "swimming pool": "🏊",
        "pool": "🏊",
        "water polo": "🤽‍♀️",
        "netball": "🏐",
        "box": "🥊",
        "jersey": "🎽",
        "goal": "🥅",
        "goalkeeper": "🥅",
        "goalie": "🥅",
        "kite": "🪁",
        "rugby": "🏉",
        "frisbee": "🥏",
        "yoyo": "🪀",
        "dart": "🎯",
        "bowling": "🎳",
        "badminton": "🏸",
        "ball": "🏀",
        "boomerang": "🪃",
        "skateboard": "🛹",
        "fight": "⚔️",
        "fence": "🤺",
        "run": "🏃‍♂️",
        "runner": "🏃‍♂️",
        "running": "🏃‍♂️",
        "sprint": "🏃‍♂️",
        "race": "🏃‍♂️",
        "horseriding": "🏇",
        "boat": "🛶",
        "row": "🚣",
        "rowboat": "🚣",
        "sailboat": "⛵",
        "sail": "⛵",
        "bike": "🚴",
        "bicycle": "🚴",
        "ride": "🚴",
        "win": "🏆",
        "trophy": "🏆",
        "medal": "🏅",
        "trophy cup": "🏆",
        "won": "🏆",
        "first": "🥇",
        "second": "🥈",
        "third": "🥉",
        "ticket": "🎫",
        "circus tent": "🎪",
        "circus": "🎪",
        "clown": "🤡",
        "clown face": "🤡",
        "juggle": "🤹",
        "juggling": "🤹",
        "comedy": "🤡",
        "drama": "🎭",
        "musical": "🎭",
        "musical note": "🎼",
        "ballet": "🩰",
        "paint": "🎨",
        "art": "🎨",
        "action": "🎬",
        "mic": "🎤",
        "microphone": "🎤",
        "headphones": "🎧",
        "speaker": "🎤",
        "sound": "🎧",
        "soundwave": "🎧",
        "piano": "🎹",
        "electric guitar": "🎸",
        "guitar": "🎸",
        "violin": "🎻",
        "trumpet": "🎺",
        "saxophone": "🎷",
        "drum": "🥁",
        "shaker": "🪇",
        "accordion": "🪗",
        "banjo": "🪕",
        "recorder": "🪈",
        "flute": "🪈",
        "dice": "🎲",
        "game die": "🎲",
        "slot machine": "🎰",
        "slot": "🎰",
        "chess piece": "♟️",
        "pawn": "♟️",
        "chess": "♟️",
        "chessboard": "🏁",
        "dart board": "🎯",
        "music": "🎼",        


        #travel and places
        "car": "🚗",
        "bus": "🚌",
        "train": "🚆",
        "plane": "✈️",
        "rocket": "🚀",
        "bicycle": "🚲",
        "motorcycle": "🏍️",
        "truck": "🚚",
        "ambulance": "🚑",
        "firetruck": "🚒",
        "police car": "🚓",
        "taxi": "🚕",
        "helicopter": "🚁",

        #places
        "city": "🏙️",
        "skyscraper": "🏢",
        "office": "🏢",
        "house": "🏠",
        "home": "🏡",
        "hotel": "🏨",
        "hospital": "🏥",
        "school": "🏫",
        "bank": "🏦",
        "post office": "🏤",
        "store": "🏬",
        "shop": "🛒",
        "factory": "🏭",
        "warehouse": "🏗️",
        "train station": "🚉",
        "bus stop": "🚏",
        "airport": "✈️",
        "church": "⛪",
        "mosque": "🕌",
        "temple": "🛕",
        "synagogue": "🕍",
        "castle": "🏰",
        "fort": "🏯",
        "library": "📚",
        "museum": "🏛️",
        "theater": "🎭",
        "stadium": "🏟️",

        # 🌲 Nature & Outdoor Places
        "forest": "🌲",
        "woods": "🌳",
        "jungle": "🌴",
        "mountain": "⛰️",
        "mount": "⛰️",
        "volcano": "🌋",
        "beach": "🏖️",
        "desert": "🏜️",
        "island": "🏝️",
        "waterfall": "🌊",
        "river": "🏞️",
        "lake": "🏕️",
        "ocean": "🌊",
        "cave": "🕳️",
        "park": "🏞️",
        "garden": "🏡",
        "farm": "🚜",
        "road": "🛣️",
        "highway": "🛤️",
        "bridge": "🌉",
        "tunnel": "🚇",
        "gas station": "⛽",
        "car park": "🅿️",
        "amusement park": "🎡",
        "theme park": "🎢",
        "zoo": "🦁",
        "aquarium": "🐠",
        "arcade": "🕹️",
        "casino": "🎰",
        "bowling alley": "🎳",
        "restaurant": "🍽️",
        "cafe": "☕",
        "bar": "🍻",
        "nightclub": "🎶",
        "cinema": "🎬",
        "ski resort": "⛷️",
        "golf course": "⛳",
        "tennis court": "🎾",
        "basketball court": "🏀",
        "football stadium": "⚽",
        "race track": "🏁",
        "statue of liberty": "🗽",
        "eiffel tower": "🗼",
        "big ben": "🕰️",
        "great wall": "🧱",
        "pyramids": "🔺",
        "taj mahal": "🏛️",
        "mount fuji": "🗻",

        #objects
        "xmas": "🎅",
        "christmas": "🎅",
        "santa": "🎅",
        "fireworks": "🎆",
        "sparkler": "🎇",
        "balloon": "🎈",
        "tada": "🎉",
        "confetti": "🎊",
        "santa claus": "🎅",
        "gift": "🎁",
        "gift box": "🎁",
        "st nicks": "🎅",
        "st nicholas": "🎅",
        "microscope": "🔬",
        "telescope": "🔭",
        "dna": "🧬",
        "rna": "🧬",
        "atom": "⚛️",
        "test tube": "🧪",
        "math": "➗",
        "divide": "➗",
        "calculator": "🧮",
        "hammer": "🔨",
        "wrench": "🔧",
        "screwdriver": "🪛",
        "saw": "🪚",
        "axe": "🪓",
        "drill": "🛠️",
        "ruler": "📏",
        "measure": "📏",
        "toolbox": "🧰",
        "fix": "🧰",
        "money": "💰",
        "wallet": "👛",
        "credit card": "💳",
        "coin": "🪙",
        "change": "🪙",
        "bank": "🏦",
        "chart": "📈",
        "receipt": "🧾",
        "pen": "🖊️",
        "write": "🖊️",
        "pencil": "✏️",
        "book": "📖",
        "notebook": "📓",
        "paper": "📄",
        "clipboard": "📋",
        "memo": "📝",
        "calendar": "📅",
        "date": "📆",
        "today": "📅",
        "day": "📅",
        "month": "📆",
        "year": "📆",
        "tmr": "📅",
        "tomorrow": "📅",
        "yesterday": "📅",
        "envelope": "✉️",
        "mail": "📬",
        "package": "📦",
        "scissors": "✂️",
        "tape": "🩹",
        "stapler": "📎",
        "phone": "📱",
        "computer": "💻",
        "laptop": "💻",
        "desktop": "🖥️",
        "keyboard": "⌨️",
        "tv": "📺",
        "remote": "🕹️",
        "radio": "📻",
        "watch": "⌚",
        "alarm": "⏰",
        "urgent": "⏰",
        "clock": "🕰️",
        "timer": "⏱️",
        "stopwatch": "⏱️",
        "hourglass": "⌛",
        "time": "⏳",
        "camera": "📷",
        "lightbulb": "💡",
        "idea": "💡",
        "bulb": "💡",
        "flashlight": "🔦",
        "flash": "🔦",
        "candle": "🕯️",
        "candlestick": "🕯️",
        "cigarette": "🚬",
        "smoking": "🚬",
        "coffin": "⚰️",
        "funeral": "⚰️",
        "torch": "🔦",
        "battery": "🔋",
        "charge": "🔋",
        "plug": "🔌",
        "cable": "🔌",
        "printer": "🖨️",
        "print" : "🖨️",
        "lamp": "🛋️",
        "lantern": "🏮",
        "light": "💡",
        "couch": "🛋️",
        "chair": "🪑",
        "bed": "🛏️",
        "mirror": "🪞",
        "door": "🚪",
        "window": "🪟",
        "toilet": "🚽",
        "shower": "🚿",
        "bathtub": "🛁",
        "toothbrush": "🪥",
        "soap": "🧼",
        "clean": "🧼",
        "wash": "🧼",
        "bath": "🛁",
        "sink": "🚽",
        "bathroom": "🛁",
        "tub": "🛁",
        "towel": "🛀",
        "razor": "🪒",
        "plunger": "🪠",
        "photo": "📷",
        "photograph": "📷",
        "picture": "📷",
        "pic": "📷",

        #plants and animals
        "long": "📏",
        "animal": "🐶",
        "ass": "🫏",
        "dog": "🐶",
        "cat": "🐱",
        "bird": "🐦",
        "fish": "🐟",
        "mouse": "🐭",
        "puppy": "🐶",
        "kitten": "🐱",
        "rabbit": "🐰",
        "bunny": "🐰",
        "turtle": "🐢",
        "snake": "🐍",
        "lizard": "🦎",
        "tiger": "🐯",
        "lion": "🦁",
        "bear": "🐻",
        "monkey": "🐵",
        "gorilla": "🦍",
        "zebra": "🦓",
        "elephant": "🐘",
        "giraffe": "🦒",
        "kangaroo": "🦘",
        "panda": "🐼",
        "koala": "🐨",
        "beaver": "🦫",
        "dolphin": "🐬",
        "whale": "🐳",
        "shark": "🦈",
        "octopus": "🐙",
        "turkey": "🦃",
        "chicken": "🐔",
        "duck": "🦆",
        "cow": "🐄",
        "pig": "🐖",
        "horse": "🐎",
        "sheep": "🐑",
        "goat": "🐐",
        "rooster": "🐓",
        "pup": "🐶",
        "kitty": "🐱",
        "chick": "🐥",
        "penguin": "🐧",
        "flamingo": "🦩",
        "owl": "🦉",
        "eagle": "🦅",
        "duckling": "🐤",
        "peacock": "🦚",
        "parrot": "🦜",
        "swan": "🦢",
        "ant": "🐜",
        "bee": "🐝",
        "butterfly": "🦋",
        "bug": "🐛",
        "beetle": "🐞",
        "mosquito": "🦟",
        "fly": "🪰",
        "spider": "🕷️",
        "scorpion": "🦂",
        "ladybird": "🐞",
        "unicorn": "🦄",
        "dragon": "🐉",
        "cockroach": "🦗",
        "spiderweb": "🕸️",
        "web": "🕸️",
        "roach": "🪳",
        "t-rex": "🦖",
        "dinosaur": "🦖",
        "dino": "🦖",
        "crow": "🐦‍⬛",
        "raven": "🐦‍⬛",
        "snail": "🐌",
        "slug": "🐌",
        "wolf": "🐺",
        "fox": "🦊",
        "crab": "🦀",
        "lobster": "🦞",
        "shrimp": "🦐",
        "squid": "🦑",
        "tentacles": "🦑",
        "frog": "🐸",
        "toad": "🐸",
        "polar bear": "🐻‍❄️",
        "orangutan": "🦧",
        "rhinoceros": "🦏",
        "hippopotamus": "🦛",
        "hippo": "🦛",
        "rhino" : "🦏",
        "camel": "🐫",
        "llama": "🦙",
        "alpaca": "🦙",
        "cheetah": "🐆",
        "leopard": "🐆",
        "dodo bird": "🦤",
        "dodo": "🦤",
        "racoon": "🦝",
        "feather": "🪶",
        "snout": "🐽",
        "worm": "🪱",
        "crickets": "🦗",
        "cicada": "🦗",
        "jellyfish": "🪼",
        "coral": "🪸",
        "poodle": "🐩",
        "dove": "🕊️",
        "sloth": "🦥",
        "otter": "🦦",
        "skunk": "🦨",
        "badger": "🦡",
        "phoenix": "🐦‍🔥",
        "firebird": "🐦‍🔥",
        "paw prints": "🐾",
        "paw": "🐾",
        "squirrel": "🐿️",
        "chipmunk": "🐿️",
        "hedgehog": "🦔",
        "porcupette": "🦔",
        "porcupine": "🦔",
        "wing": "🪽",
        "wingtip": "🪽",
        "bison": "🦬",
        "hare": "🐰",
        "ram": "🐂",
        "ox": "🐃",
        "water buffalo": "🐃",
        "buffalo": "🐃",
        "bull": "🐃",
        "nest": "🪹",
        "hog": "🐖",
        "mammoth": "🦣",
        "pufferfish": "🐡",
        "clownfish": "🐠",
        "tuna": "🐟",
        "moose": "🫎",
        "elk": "🦌",
        "deer": "🦌",
        "reindeer": "🦌",
        "log": "🪵",
        "leaf": "🍃",
        "grass": "🌿",
        "tree": "🌳",
        "palm tree": "🌴",
        "evergreen tree": "🌲",
        "deciduous tree": "🌲",
        "palm frond": "🌴",
        "palm": "🌴",
        "bamboo": "🎍",
        "leaves": "🍃",
        "vine": "🌿",
        "bush": "🌳",
        "christmas tree": "🎄",
        "xmas tree": "🎄",
        "mushroom": "🍄",
        "lotus" : "🪷",
        "cactus": "🌵",
        "daisy": "🌼",
        "sunflower": "🌻",
        "rose": "🌹",
        "hibiscus": "🌺",
        "tulip": "🌷",
        "blossom": "🌼",
        "cherry blossom": "🌸",
        "bouquet": "💐",
        "rose bouquet": "💐",
        "fungi": "🍄‍🟫",
        "carnation": "🌻",
        "wilt": "🥀",
        "wilted": "🥀",
        "lavender": "🪻",
        "baby's breath": "🪻",
        "babys breath": "🪻",
        "shell": "🐚",
        "seashell": "🐚",
        "starfish": "⭐️",
        "conch": "🐚",
        "full moon": "🌕",
        "new moon": "🌚",
        "crescent": "🌘",
        "star": "⭐️",
        "shooting star": "🌠",
        "starry night": "🌃",
        "night": "🌃",
        "half moon": "🌓",
        "sun": "🌞",
        "moon": "🌝",
        "saturn": "🪐",
        "jupiter": "🪐",
        "uranus": "🪐",
        "neptune": "🪐",
        "pluto": "🪐",
        "mars": "🪐",
        "mercury": "🪐",
        "venus": "🪐",
        "earth": "🌍",
        "globe": "🌎",
        "planet": "🪐",
        "shine bright": "🌟",
        "shine": "🌟",
        "bright": "🌟",
        "starry": "🌟",
        "twinkle": "✨",
        "sparkle": "✨",
        "lightning": "⚡️",
        "thunder": "⛈️",
        "rain": "🌧️",
        "zap": "⚡️",
        "thunderstorm": "⛈️",
        "cloud": "☁️",
        "cloudy": "☁️",
        "cloudy with a chance of meatballs": "🍝",
        "cyclone": "🌀",
        "hurricane": "🌪",
        "tornado": "🌪",
        "fog": "🌫",
        "mist": "🌫",
        "foggy": "🌫",
        "misty": "🌫",
        "wind": "🌬",
        "windy": "🌬",
        "breeze": "🌬",
        "gale": "🌬",
        "storm": "⛈️",
        "umbrella": "☂️",
        "wave": "🌊",
        "droplet": "💧",
        "drop" : "💧",
        "rainbow": "🌈",
        "colourful": "🌈",
        "gay": "🏳️‍🌈",
        "bubble": "🫧",
        "bubbly": "🫧",
        "snowman": "⛄️",
        "snow": "❄️",
        "snowflake": "❄️",
        "fast": "💨",
        "quick": "💨",
        "speedy": "💨",
        "speed": "💨",
        "quickly": "💨",
        "swift": "💨",
        "swiftly": "💨",
        "swiftness": "💨",
        "quickness": "💨",
        "meteor": "☄️",
        "asteroid": "☄️",
        "meteor shower": "☄️",
        "tide": "🌊",
}

def translate_to_emoji(word: str):
    # Check for the word in the dictionary (singular or plural)
    if word in emoji_dict:
        return emoji_dict[word]

    # Handle plural words (by removing the trailing 's')
    if word.endswith('s'):
        singular_word = word[:-1]  # Remove 's' from the end
        if singular_word in emoji_dict:
            return emoji_dict[singular_word]

    # If no match is found, return the original word
    return word


async def emoji_lang(update: Update, context: CallbackContext):
    if not context.args:  # If user didn't provide any text
        await update.message.reply_text("Please provide a sentence! Example: /emoji_lang I love dogs")
        return

    words = " ".join(context.args).lower().split()  # Convert input to lowercase and split into words
    translated_sentence = []

    for word in words:
        # Use the translate_to_emoji function for each word
        translated_sentence.append(translate_to_emoji(word))

    response = " ".join(translated_sentence)  # Join words back into a sentence
    await update.message.reply_text(f"Translated: {response}")


async def help_command(update: Update, context: CallbackContext):
    commands = "/start - Start the bot\n" \
               "/cheat - Try to cheat? Not today.\n" \
               "/rickroll - ???\n" \
               "/mood - What's your vibe?\n" \
               "/flip - Flip a coin\n" \
               "/insult - Get roasted\n"\
               "/death - Wanna play Russian Roulette?\n"\
               "/emoji - Translate a word to emoji\n"\
    
    await update.message.reply_text(f"Available commands:\n{commands}")


def main():
    app = Application.builder().token(TOKEN).build()

    app.add_handler(CommandHandler("start", start))
    app.add_handler(CommandHandler("cheat", cheat))
    app.add_handler(CommandHandler("rickroll", rickroll))
    app.add_handler(CommandHandler("mood", mood))
    app.add_handler(CommandHandler("flip", flip))
    app.add_handler(CommandHandler("insult", insult))
    app.add_handler(CommandHandler("death", death))
    app.add_handler(CommandHandler("emoji", emoji_lang))
    app.add_handler(CommandHandler("help", help_command))

    app.run_polling()

if __name__ == "__main__":
    main()

